package com.shibalearning.entity.enu;

public enum ExceptionCode {
    FEED_BACK_NOT_FOUND,
    LESSON_NOT_FOUND,
    REGISTRATION_NOT_FOUND,
    ROLE_NOT_FOUND,
    USER_NOT_FOUND,
    GRADE_NOT_FOUND,
    SUBJECT_NOT_FOUND,
    COURSE_NOT_FOUND,
    RATE_INVALID,
    USER_NAME_EXIST,
    EMAIL_EXIST,
    REGISTRATION_EXISTED,
    FEEDBACK_EXISTED,
    SUCCESS,
    FAIL
}
